export const MOCK_DATA = [
  { id: "zoho-corp", name: "Zoho Corporation Private Limited", industry: "SaaS & Cloud", location: "Chennai, Tamil Nadu", cin: "U72200TN1996PTC035345", estYear: 1996, status: "Active" },
  { id: "flipkart", name: "Flipkart Internet Private Limited", industry: "E-commerce", location: "Bangalore, Karnataka", cin: "U51109KA2012PTC066107", estYear: 2012, status: "Active" },
  { id: "razorpay", name: "Razorpay Software Private Limited", industry: "Fintech", location: "Bangalore, Karnataka", cin: "U72200KA2014PTC077308", estYear: 2014, status: "Active" },
  { id: "google-india", name: "Google India Private Limited", industry: "IT Services", location: "Gurugram, Haryana", cin: "U72200KA2003PTC033028", estYear: 2003, status: "Active" },
  { id: "dream11", name: "Sporta Technologies Private Limited", industry: "Gaming & Sports Tech", location: "Mumbai, Maharashtra", cin: "U74900MH2008PTC184124", estYear: 2008, status: "Active" },
  { id: "tcs", name: "Tata Consultancy Services Limited", industry: "IT Services", location: "Mumbai, Maharashtra", cin: "L22210MH1995PLC084781", estYear: 1995, status: "Active" },
  { id: "infosys", name: "Infosys Limited", industry: "IT Services", location: "Bangalore, Karnataka", cin: "L85110KA1981PLC013115", estYear: 1981, status: "Active" },
  { id: "wipro", name: "Wipro Limited", industry: "IT Services", location: "Bangalore, Karnataka", cin: "L32102KA1945PLC020800", estYear: 1945, status: "Active" },
  { id: "hcl-tech", name: "HCL Technologies Limited", industry: "IT Services", location: "Noida, Uttar Pradesh", cin: "L74140DL1991PLC046369", estYear: 1991, status: "Active" },
  { id: "tech-mahindra", name: "Tech Mahindra Limited", industry: "IT Services", location: "Pune, Maharashtra", cin: "L64200MH1986PLC041370", estYear: 1986, status: "Active" },
  { id: "freshworks", name: "Freshworks Technologies Private Limited", industry: "SaaS", location: "Chennai, Tamil Nadu", cin: "U72200TN2010PTC076534", estYear: 2010, status: "Active" },
  { id: "ola-cabs", name: "ANI Technologies Private Limited (OlaCabs)", industry: "Mobility Tech", location: "Bangalore, Karnataka", cin: "U60200KA2010PTC057715", estYear: 2010, status: "Active" },
  { id: "swiggy", name: "Bundl Technologies Private Limited (Swiggy)", industry: "Food Tech", location: "Bangalore, Karnataka", cin: "U63040KA2013PTC138743", estYear: 2013, status: "Active" },
  { id: "zomato", name: "Zomato Limited", industry: "Food Tech", location: "Gurugram, Haryana", cin: "L74899HR2010PLC045149", estYear: 2010, status: "Active" },
  { id: "paytm", name: "One97 Communications Limited (Paytm)", industry: "Fintech", location: "Noida, Uttar Pradesh", cin: "L72200UP2000PLC024528", estYear: 2000, status: "Active" },
  { id: "phonepe", name: "PhonePe Private Limited", industry: "Fintech", location: "Bangalore, Karnataka", cin: "U74999KA2015PTC083879", estYear: 2015, status: "Active" },
  { id: "meesho", name: "Fashnear Technologies Private Limited (Meesho)", industry: "E-commerce", location: "Bangalore, Karnataka", cin: "U72900KA2015PTC082147", estYear: 2015, status: "Active" },
  { id: "nykaa", name: "FSN E-Commerce Ventures Limited (Nykaa)", industry: "Beauty & E-commerce", location: "Mumbai, Maharashtra", cin: "U52600MH2012PLC230659", estYear: 2012, status: "Active" },
  { id: "byju", name: "Think & Learn Private Limited (BYJU'S)", industry: "EdTech", location: "Bangalore, Karnataka", cin: "U80903KA2011PTC057982", estYear: 2011, status: "Active" },
  { id: "cred", name: "Dreamplug Technologies Private Limited (CRED)", industry: "Fintech", location: "Bangalore, Karnataka", cin: "U72900KA2018PTC110891", estYear: 2018, status: "Active" },
  { id: "groww", name: "Nextbillion Technology Private Limited (Groww)", industry: "Fintech", location: "Bangalore, Karnataka", cin: "U65999KA2016PTC091951", estYear: 2016, status: "Active" },
  { id: "zepto", name: "Kiranakart Technologies Private Limited (Zepto)", industry: "Quick Commerce", location: "Mumbai, Maharashtra", cin: "U63040MH2021PTC360139", estYear: 2021, status: "Active" },
  { id: "reliance", name: "Reliance Industries Limited", industry: "Conglomerate", location: "Mumbai, Maharashtra", cin: "L17110MH1973PLC019786", estYear: 1973, status: "Active" },
  { id: "tata-steel", name: "Tata Steel Limited", industry: "Steel & Metals", location: "Mumbai, Maharashtra", cin: "L27100MH1907PLC000260", estYear: 1907, status: "Active" },
  { id: "mahindra", name: "Mahindra & Mahindra Limited", industry: "Automobile & Conglomerate", location: "Mumbai, Maharashtra", cin: "L65990MH1945PLC004558", estYear: 1945, status: "Active" },
  { id: "larsen-toubro", name: "Larsen & Toubro Limited", industry: "Engineering & Construction", location: "Mumbai, Maharashtra", cin: "L99999MH1946PLC004768", estYear: 1946, status: "Active" },
  { id: "adani-enterprises", name: "Adani Enterprises Limited", industry: "Conglomerate", location: "Ahmedabad, Gujarat", cin: "L51100GJ1993PLC019067", estYear: 1993, status: "Active" },
  { id: "maruti", name: "Maruti Suzuki India Limited", industry: "Automobile", location: "New Delhi, Delhi", cin: "L34103DL1981PLC011375", estYear: 1981, status: "Active" },
  { id: "hero-motocorp", name: "Hero MotoCorp Limited", industry: "Two-Wheeler", location: "New Delhi, Delhi", cin: "L35911DL1984PLC017354", estYear: 1984, status: "Active" },
  { id: "bajaj-auto", name: "Bajaj Auto Limited", industry: "Two-Wheeler", location: "Pune, Maharashtra", cin: "L65993PN2007PLC130076", estYear: 2007, status: "Active" },
  { id: "tata-motors", name: "Tata Motors Limited", industry: "Automobile", location: "Mumbai, Maharashtra", cin: "L28920MH1945PLC004520", estYear: 1945, status: "Active" },
  { id: "sun-pharma", name: "Sun Pharmaceutical Industries Limited", industry: "Pharmaceuticals", location: "Mumbai, Maharashtra", cin: "L24230GJ1993PLC019050", estYear: 1993, status: "Active" },
  { id: "dr-reddys", name: "Dr. Reddy's Laboratories Limited", industry: "Pharmaceuticals", location: "Hyderabad, Telangana", cin: "L85195TG1984PLC004507", estYear: 1984, status: "Active" },
  { id: "cipla", name: "Cipla Limited", industry: "Pharmaceuticals", location: "Mumbai, Maharashtra", cin: "L24239MH1935PLC002380", estYear: 1935, status: "Active" },
  { id: "apollo-hospitals", name: "Apollo Hospitals Enterprise Limited", industry: "Healthcare", location: "Chennai, Tamil Nadu", cin: "L85110TN1979PLC008035", estYear: 1979, status: "Active" },
  { id: "hindustan-unilever", name: "Hindustan Unilever Limited", industry: "FMCG", location: "Mumbai, Maharashtra", cin: "L15140MH1933PLC002030", estYear: 1933, status: "Active" },
  { id: "itc", name: "ITC Limited", industry: "FMCG & Conglomerate", location: "Kolkata, West Bengal", cin: "L16005WB1910PLC001985", estYear: 1910, status: "Active" },
  { id: "nestle-india", name: "Nestle India Limited", industry: "FMCG", location: "Gurugram, Haryana", cin: "L15202HR1959FLC008085", estYear: 1959, status: "Active" },
  { id: "dabur", name: "Dabur India Limited", industry: "FMCG & Ayurveda", location: "New Delhi, Delhi", cin: "L24230DL1975PLC007196", estYear: 1975, status: "Active" },
  { id: "hdfc-bank", name: "HDFC Bank Limited", industry: "Banking", location: "Mumbai, Maharashtra", cin: "L65920MH1994PLC080618", estYear: 1994, status: "Active" },
  { id: "icici-bank", name: "ICICI Bank Limited", industry: "Banking", location: "Mumbai, Maharashtra", cin: "L65190GJ1994PLC021012", estYear: 1994, status: "Active" },
  { id: "axis-bank", name: "Axis Bank Limited", industry: "Banking", location: "Ahmedabad, Gujarat", cin: "L65110GJ1993PLC020769", estYear: 1993, status: "Active" },
  { id: "sbi", name: "State Bank of India", industry: "Banking (PSU)", location: "Mumbai, Maharashtra", cin: "L65190MH1955GOI009476", estYear: 1955, status: "Active" },
  { id: "ongc", name: "Oil and Natural Gas Corporation Limited", industry: "Oil & Gas (PSU)", location: "New Delhi, Delhi", cin: "L74899DL1993GOI054155", estYear: 1993, status: "Active" },
  { id: "ntpc", name: "NTPC Limited", industry: "Power Generation (PSU)", location: "New Delhi, Delhi", cin: "L40101DL1975GOI007966", estYear: 1975, status: "Active" },
  { id: "airtel", name: "Bharti Airtel Limited", industry: "Telecommunications", location: "New Delhi, Delhi", cin: "L74899DL1995PLC070609", estYear: 1995, status: "Active" },
  { id: "jio", name: "Reliance Jio Infocomm Limited", industry: "Telecommunications", location: "Mumbai, Maharashtra", cin: "U72900MH2007PLC168021", estYear: 2007, status: "Active" },
  { id: "delhivery", name: "Delhivery Limited", industry: "Logistics & Supply Chain", location: "Gurugram, Haryana", cin: "L63000HR2011PLC044136", estYear: 2011, status: "Active" },
  { id: "falcon-ebiz", name: "Falcon Ebiz Private Limited", industry: "IT Services & Data", location: "Thane, Maharashtra", cin: "U72900MH2016PTC281055", estYear: 2016, status: "Active" },
  { id: "technova-solutions", name: "TechNova Solutions Private Limited", industry: "AI & Cloud", location: "Bangalore, Karnataka", cin: "U72900KA2021PTC145000", estYear: 2021, status: "Active" },
  { id: "greenfuture-energy", name: "GreenFuture Energy Private Limited", industry: "Renewables", location: "Mumbai, Maharashtra", cin: "U40106MH2019PTC320111", estYear: 2019, status: "Active" },
  { id: "bluefin-logistics", name: "BlueFin Logistics Private Limited", industry: "E-commerce Logistics", location: "Gurugram, Haryana", cin: "U63090HR2018PTC075000", estYear: 2018, status: "Active" },
  { id: "spinny", name: "Cartisan Technology Private Limited (Spinny)", industry: "Auto Tech", location: "Gurugram, Haryana", cin: "U74999HR2015PTC055527", estYear: 2015, status: "Active" },
  { id: "lenskart", name: "Lenskart Solutions Private Limited", industry: "Eyewear & Retail", location: "New Delhi, Delhi", cin: "U52100DL2009PTC194839", estYear: 2009, status: "Active" },
  { id: "mamaearth", name: "Honasa Consumer Limited (Mamaearth)", industry: "FMCG & D2C", location: "Gurugram, Haryana", cin: "L72900HR2016PLC063752", estYear: 2016, status: "Active" },
];

export function getCompanyLogo(id) {
  const logos = {
    "zoho-corp": "https://logo.clearbit.com/zoho.com",
    "flipkart": "https://logo.clearbit.com/flipkart.com",
    "razorpay": "https://logo.clearbit.com/razorpay.com",
    "google-india": "https://logo.clearbit.com/google.com",
    "dream11": "https://logo.clearbit.com/dream11.com",
    "tcs": "https://logo.clearbit.com/tcs.com",
    "infosys": "https://logo.clearbit.com/infosys.com",
    "wipro": "https://logo.clearbit.com/wipro.com",
    "hcl-tech": "https://logo.clearbit.com/hcltech.com",
    "tech-mahindra": "https://logo.clearbit.com/techmahindra.com",
    "freshworks": "https://logo.clearbit.com/freshworks.com",
    "ola-cabs": "https://logo.clearbit.com/olacabs.com",
    "swiggy": "https://logo.clearbit.com/swiggy.com",
    "zomato": "https://logo.clearbit.com/zomato.com",
    "paytm": "https://logo.clearbit.com/paytm.com",
    "phonepe": "https://logo.clearbit.com/phonepe.com",
    "meesho": "https://logo.clearbit.com/meesho.com",
    "nykaa": "https://logo.clearbit.com/nykaa.com",
    "byju": "https://logo.clearbit.com/byjus.com",
    "cred": "https://logo.clearbit.com/cred.club",
    "groww": "https://logo.clearbit.com/groww.in",
    "zepto": "https://logo.clearbit.com/zepto.cash",
    "reliance": "https://logo.clearbit.com/ril.com",
    "tata-steel": "https://logo.clearbit.com/tatasteel.com",
    "mahindra": "https://logo.clearbit.com/mahindra.com",
    "larsen-toubro": "https://logo.clearbit.com/larsentoubro.com",
    "adani-enterprises": "https://logo.clearbit.com/adani.com",
    "maruti": "https://logo.clearbit.com/marutisuzuki.com",
    "hero-motocorp": "https://logo.clearbit.com/heromotocorp.com",
    "bajaj-auto": "https://logo.clearbit.com/bajajauto.com",
    "tata-motors": "https://logo.clearbit.com/tatamotors.com",
    "sun-pharma": "https://logo.clearbit.com/sunpharma.com",
    "dr-reddys": "https://logo.clearbit.com/drreddys.com",
    "cipla": "https://logo.clearbit.com/cipla.com",
    "apollo-hospitals": "https://logo.clearbit.com/apollohospitals.com",
    "hindustan-unilever": "https://logo.clearbit.com/hul.co.in",
    "itc": "https://logo.clearbit.com/itcportal.com",
    "nestle-india": "https://logo.clearbit.com/nestle.in",
    "dabur": "https://logo.clearbit.com/dabur.com",
    "hdfc-bank": "https://logo.clearbit.com/hdfcbank.com",
    "icici-bank": "https://logo.clearbit.com/icicibank.com",
    "axis-bank": "https://logo.clearbit.com/axisbank.com",
    "sbi": "https://logo.clearbit.com/sbi.co.in",
    "ongc": "https://logo.clearbit.com/ongcindia.com",
    "ntpc": "https://logo.clearbit.com/ntpc.co.in",
    "airtel": "https://logo.clearbit.com/airtel.in",
    "jio": "https://logo.clearbit.com/jio.com",
    "delhivery": "https://logo.clearbit.com/delhivery.com",
    "falcon-ebiz": "https://logo.clearbit.com/falconebiz.com",
    "spinny": "https://logo.clearbit.com/spinny.com",
    "lenskart": "https://logo.clearbit.com/lenskart.com",
    "mamaearth": "https://logo.clearbit.com/mamaearth.in",
  };
  return logos[id] || null;
}
